"""
Mingle the two paths to find 2 new paths
Permute combination of both paths
"""
from computedist import dist
import csv
fans1=[]
fans2=[]
"""
Read paths generated by LKH
"""
for i in range(6):
	for j in range(6):
		problem=str(i)+str(j)
		with open("../LKH/path1/ans"+problem+".csv","rb") as f:
			add=[int(k[0]) for k in csv.reader(f)]
			add.reverse()
			fans1.append(add)

for i in range(6):
	for j in range(6):
		problem=str(i)+str(j)
		with open("../LKH/path2/ans"+problem+".csv","rb") as f:
			add=[int(k[0]) for k in csv.reader(f)]
			add.reverse()
			fans2.append(add)
combs=[]
for i in xrange(2**35,2**36):
    a=bin(i)
    #print a[2:]
    if str(a[2:]).count('1')==8:
        combs.append(a[2:])

cnt=0
print len(fans1)
for i in combs:
	mingle1=[]
	mingle2=[]
	print i
	for j in i:
		if j=='0':
			mingle1+=fans1[cnt]
			mingle2+=fans2[cnt]
		else:
			mingle1+=fans2[cnt]
			mingle2+=fans1[cnt]
		cnt+=1
	print len(mingle1)
	print dist(mingle1),dist(mingle2)
exit()
with csv.writer(open("mingle/mingle1.csv","wb")) as f:
	f.writerows(mingle1)
with csv.writer(open("mingle/mingle2.csv","wb")) as f:
	f.writerows(mingle2)